packages:
  - "backend/*"
  - "store"
  - "store-management"
allowBuilds:
  esbuild: true
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
